/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MisclassificationsRouteImport } from './routes/misclassifications'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MisclassificationsRoute = MisclassificationsRouteImport.update({
  id: '/misclassifications',
  path: '/misclassifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/architecture': typeof ArchitectureRoute
  '/knowledge': typeof KnowledgeRoute
  '/misclassifications': typeof MisclassificationsRoute
  '/performance': typeof PerformanceRoute
  '/project': typeof ProjectRoute
  '/records': typeof RecordsRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/architecture': typeof ArchitectureRoute
  '/knowledge': typeof KnowledgeRoute
  '/misclassifications': typeof MisclassificationsRoute
  '/performance': typeof PerformanceRoute
  '/project': typeof ProjectRoute
  '/records': typeof RecordsRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/architecture': typeof ArchitectureRoute
  '/knowledge': typeof KnowledgeRoute
  '/misclassifications': typeof MisclassificationsRoute
  '/performance': typeof PerformanceRoute
  '/project': typeof ProjectRoute
  '/records': typeof RecordsRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/architecture'
    | '/knowledge'
    | '/misclassifications'
    | '/performance'
    | '/project'
    | '/records'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/architecture'
    | '/knowledge'
    | '/misclassifications'
    | '/performance'
    | '/project'
    | '/records'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/architecture'
    | '/knowledge'
    | '/misclassifications'
    | '/performance'
    | '/project'
    | '/records'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ArchitectureRoute: typeof ArchitectureRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MisclassificationsRoute: typeof MisclassificationsRoute
  PerformanceRoute: typeof PerformanceRoute
  ProjectRoute: typeof ProjectRoute
  RecordsRoute: typeof RecordsRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misclassifications': {
      id: '/misclassifications'
      path: '/misclassifications'
      fullPath: '/misclassifications'
      preLoaderRoute: typeof MisclassificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ArchitectureRoute: ArchitectureRoute,
  KnowledgeRoute: KnowledgeRoute,
  MisclassificationsRoute: MisclassificationsRoute,
  PerformanceRoute: PerformanceRoute,
  ProjectRoute: ProjectRoute,
  RecordsRoute: RecordsRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
